### ISSUE TITLE
[요양보호사 / 보호자] Line messaging API 고도화 

### ISSUE THREAD

**Issue by pykido** [kakao-tech-campus-2nd-step3/Team13_BE#40]
### 1. 보호자에게 알림 보내기 (매일 오후 6시)
- [x] 정해진 시간에 차트 보낼 때, 새롭게 작성된 일지가 없다면 "새롭게 작성된 '돌봄대상자'님의 요양 일지 내용이 없습니다."라고 보내기 

### 2. 보호자, 요양보호사 정보를 관리자 페이지에서 등록할 때 알림 시간을 정할 수 있어야 함 (정하지 않는다면 default로)
- [x] 기본적인 알림 시간 default값은 요양보호사는 오후 5시, 보호자는 오전 9시로 설정하기 
- [x] 추가적으로 관리자 페이지에서 등록 혹은 수정할 때 알림 시간을 수정할 수 있게 엔티티 및 관련 API 수정하기 

### 3. 스케쥴러 
- [x] 5분마다 돌리자

### 4. 별개로, String에 대해서 +를 사용해서 연결하게될 경우 (+ userName +) 성능상 별로인 것으로 알고있습니다. StringBuilder, thread-safe한 경우 StringBuffer 클래스를 사용하는 건 어떤지용??
근데 스프링에서 singleton 컨셉으로 Bean들을 관리하는 것으로 알고 있는데 이부분에서 String을 그냥 사용해도 성능상 차이가 없는지? 어떤식으로 적용될지는 명확하게 모르겠습니다...ㅎㅎ;;
- [x] 메시지 수정하기 

### 5. handleLineEvent 메서드에서 
throw 되는 ApplicationException과 그냥 Exception을 서로 다르게 catch하는 것은 어떤지요??
ApplicationException은 비즈니스상 예상된 예외라서 처리로직이 명확하고, 그외 예상치 못한 Exception은 따로 추가적인 대책이 필요할 것 같습니당

### 6. 멘토링 내용 반영하기 
- ⭐️⭐️⭐️ 추가적으로 단순 알림 서비스 구현에만 그치지 않고 ‘서버의 문제로 알림 메시지가 아예 보내지지 않거나 알림 메시지가 2번 보내지는 상황에 대해서는 어떻게 대처할까?’라는 생각도 해보게 되었습니다.
    - Amazon sqs 혹은 RabbitMQ은 서비스를 이용하여 보내야할 알림 메시지를 큐에 명시적으로 저장하여 안정성을 높이는 방법으로 해결하고 합니다.
    - ⭐️⭐️⭐️⭐️ 이에 그치지 않고 멱등성을 고려하여 다음과 같은 방법을 추천해주셨는데 정리한 내용이 맞는지, 더 좋은 해결책이 있을지 여쭤봅니다!
        1. 알림을 보내는 트리거 발생
        2. 데이터베이스의 특정 테이블에 해당 알림 정보를 칼럼으로 넣어준다.
        3. 스케쥴러를 통해  앞서 넣은 알림 메시지 칼럼 정보들을 탐색하며 isSuccess가 false인 값들만 sqs 서비스의 큐에 넣어준다.
        4. sqs 서비스의 큐에 있는 알림 메시지들을 꺼내어 순차적으로 처리해준다.
        5. 알림 메시지 응답이 정상적으로 반환되면 앞서 저장한 칼럼의 isSuccess값을 true로 바꿔준다.

+ 추가적으로 생각해보아야 할 것들
- 요양보호사가 근무일이 아니거나 휴일일 때 알림 보내지 않아야할 듯하다.
    - 근무일 또한 ENUM으로 관리하는게 어떨까요? 예를 들어 요양보호사 A가 월, 수, 금에만 일한다면 근무일을 ENUM으로 관리하여 table에 반영하였으면 합니다!
    - 또한 요일별로 알림 시간이 다를 수도 있을 듯합니다!

### 7. sqs 붙이기
- sqs의 장점은??
    - 메시지 중복 방지 및 순서 보장 
    - 비동기 처리로 시스템 부하 감소
    - 유연한 메시지 보관 기간 및 재시도 정책
    - 자동 메시지 삭제와 중복 검사
- [x] aws에서 설정하기
- [x] 의존성 추가
- [x] 관련 코드 추가

**Comment by 20jcode** [comment]
저는 (알림관리서비스) - adapter - (라인 msg 서비스) 이런식으로 연결되면 좋을 것 같아요
/* 로직? */
?월 ?일 ??시 차트 업데이트 -> observer가 이를 catch해서 차트요약 서비스에 미리 작업해두기 (특정 시간에 batch 작업?) -> ?월 ?일 ??시 알림을 보내야할 시간이 됨 -> 알림관리서비스가 사용자가 선택한 알림서비스로 요약된 차트 정보 전송 adapter로 변환 -> (라인 서비스라면) -> 라인서비스에서 처리 후 알림 관리 서비스에 처리완료 response

약간 이런 느낌?? 이면 만약 kakao서비스로 msg서비스가 대체되더라도 해당 kakao 서비스에 맞는 adapter 만 하나 만들어주면 ok 이니까 유연한 서비스가 될 수 있을 것 같아요

1. 보호자 알림 보내기
업데이트가 없으면 보내지않아도 된다고 생각해요. // 대신에 특정 기간 이상 일지업데이트가 없다면 그 이유에 대한 처리가 필요해보입니당.
예를 들어 저희 서비스 가입 시 일주일 n회 알림서비스 제공 등의 규칙이 있을 것이고 (아마 요양원 사정마다 달라질 수 있다고 생각해요... - 법적인 최소컷만 맞춘다던지...) 해당 횟수를 만족하지 못한다면? 보호자에게 " 차트가 업데이트되지 않았어요. 해당 사유에 대해 자동 문의중이에요" => 요양보호사 혹은 요양원에 notice 주어서 해당 사유에 대해서 작성할 수 있도록?

근데 문제는 이렇게 하면 좀 작업이 많아져서... -> 일단은 없으면 "n일동안 새롭게 작성된 차트 내용이 없습니다" 로 처리해두고 추후 회의를 통해서 세밀하게 정하는건 어떤지요?

2. ENUM 좋은 것 같아요, 알림 시간 또한 따로 관리해주는거 좋은 것 같습니다.

3. 보호자 오후 7시 이쯤으로...
---
7. 스프링에서 Bean을 싱글톤으로 관리하는 것 맞습니다만, 현재 userName 이 매번 새로운 값이 들어오게되고, String은 항상 불변객체라서 새로운 userName이 포함된 구문을 매번 새로운 메모리영역으로 만들어서 할당하는 문제가 발생하지않을까요??

추가적인 궁금증

sqs가 MSA 같은 서비스에서 내부 동시성 제어? 용도로 사용되는 것 같은데, 그렇다면 msg push server를 하나 더 만들어서 사용하게 되는 것인가욧?!
